spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop
    url: jdbc:h2:~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true #System.out으로 SQL을 남긴다.
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug #logger을 통해 실행 SQL을 남긴다.
    org.hibernate.type: trace #파라미터값을 찍어준다.
